---
title: "Lab4"
author: "Tyler Smith & Ritika Agrawal"
date: "March 11, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#File Read In
library(readxl)
library(tidyr)
library(dplyr)
defense <- read_excel('cyclonesFootball2019.xlsx', sheet='Defensive')
offense <- read_excel('cyclonesFootball2019.xlsx', sheet='Offensive')
bio <- read_excel('cyclonesFootball2019.xlsx', sheet='Biography')
str(bio)
```


```{r}
#Part One

#i
defClean <- defense %>%
  mutate(Name = as.factor(Name),Opponent_Opponent=as.factor(Opponent_Opponent)) %>%
  mutate_at(c("Tackles_Solo","Tackles_ASST","Tackles_TFL","Tackles_Sack","Turnover_FF","Turnover_FR","Turnover_INT","Pass_QBH","Pass_PB"),as.numeric)

offClean <- offense %>%
  mutate(Name = as.factor(Name),Opponent_Opponent=as.factor(Opponent_Opponent)) %>%
  replace_na(list(.=0)) %>%
  mutate_at(c("Rushing_ATT","Rushing_YDS","Rushing_TD","Receiving_REC","Receiving_YDS","Receiving_TD","Passing_CMP-ATT","Passing_YDS","Passing_TD","Passing_INT"),as.numeric)

bioClean <- bio %>% 
  separate(col=Height,into=c("Feet","Inches"),sep="-") %>%
  mutate(Feet=as.numeric(Feet),Inches=as.numeric(Inches)) %>%
  mutate(Height_Inch = Feet*12+Inches) %>%
  select(-Feet,-Inches)

```

